version: '3.8'
services:
  app:
    networks:
      - traefik
      
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`test.mazbaz.fr`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=letsencryptresolver"
      
    restart: unless-stopped
    
    build: .
    
    ports:
      - '80:8000'
      
    volumes:
      - ./src:/usr/src/app
    
    command: bash -c "npm i && npx ts-node-dev --clear --poll app.ts" #remplacer par "npm i && npx ts-node app.ts" en prod (node-dev utilise du CPU)

networks:
  default:
    external:
      name: traefik
